image:
  repository: ts-dockerhub.lsst.org/mthexapod
  tag: c0029
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: summit
  LSST_SITE: summit
  OSPL_INFOFILE: /tmp/ospl-info-mtcamhexapod.log
  OSPL_ERRORFILE: /tmp/ospl-error-mtcamhexapod.log
  RUN_ARG: 1
shmemDir: /run/ospl
osplVersion: V6.10.4
