namespace: rubintv-fullcamera
fullnameOverride: u
image:
  repository: lsstts/rubintv-broadcaster
  tag: c0028_usdf
  pullPolicy: Always
env:
  DAF_BUTLER_REPOSITORY_INDEX: /project/data-repos.yaml
  http_proxy: http://sdfproxy.sdf.slac.stanford.edu:3128
  https_proxy: http://sdfproxy.sdf.slac.stanford.edu:3128
  squid_proxy: http://sdfproxy.sdf.slac.stanford.edu:3128
  no_proxy: .slac.stanford.edu
  HTTP_PROXY: http://sdfproxy.sdf.slac.stanford.edu:3128
  HTTPS_PROXY: http://sdfproxy.sdf.slac.stanford.edu:3128
  SQUID_PROXY: http://sdfproxy.sdf.slac.stanford.edu:3128
  NO_PROXY: .slac.stanford.edu
  DEPLOY_BRANCH: deploy-slac
  S3_ENDPOINT_URL: https://s3dfrgw.slac.stanford.edu
scripts:
- slac/bot/runButlerWatcher.py
- slac/bot/runMetadataServer.py
- slac/bot/runPlotter.py
- slac/bot/runIsrRunner_000.py
- slac/bot/runIsrRunner_001.py
- slac/bot/runIsrRunner_002.py
- slac/bot/runIsrRunner_003.py
- slac/bot/runIsrRunner_004.py
- slac/bot/runIsrRunner_005.py
- slac/bot/runIsrRunner_006.py
- slac/bot/runIsrRunner_007.py
- slac/bot/runIsrRunner_008.py
- slac/bot/runIsrRunner_009.py
- slac/bot/runIsrRunner_010.py
- slac/bot/runIsrRunner_011.py
- slac/bot/runIsrRunner_012.py
- slac/bot/runIsrRunner_013.py
- slac/bot/runIsrRunner_014.py
- slac/bot/runIsrRunner_015.py
- slac/bot/runIsrRunner_016.py
- slac/bot/runIsrRunner_017.py
- slac/bot/runIsrRunner_018.py
- slac/bot/runIsrRunner_019.py
- slac/bot/runIsrRunner_020.py
- slac/bot/runIsrRunner_021.py
- slac/bot/runIsrRunner_022.py
- slac/bot/runIsrRunner_023.py
- slac/bot/runIsrRunner_024.py
- slac/bot/runIsrRunner_025.py
- slac/bot/runIsrRunner_026.py
- slac/bot/runIsrRunner_027.py
- slac/bot/runIsrRunner_028.py
- slac/bot/runIsrRunner_029.py
- slac/bot/runIsrRunner_030.py
- slac/bot/runIsrRunner_031.py
- slac/bot/runIsrRunner_032.py
- slac/bot/runIsrRunner_033.py
- slac/bot/runIsrRunner_034.py
- slac/bot/runIsrRunner_035.py
- slac/bot/runIsrRunner_036.py
- slac/bot/runIsrRunner_037.py
- slac/bot/runIsrRunner_038.py
- slac/bot/runIsrRunner_039.py
- slac/bot/runIsrRunner_040.py
- slac/bot/runIsrRunner_041.py
- slac/bot/runIsrRunner_042.py
- slac/bot/runIsrRunner_043.py
- slac/bot/runIsrRunner_044.py
- slac/bot/runIsrRunner_045.py
- slac/bot/runIsrRunner_046.py
- slac/bot/runIsrRunner_047.py
- slac/bot/runIsrRunner_048.py
- slac/bot/runIsrRunner_049.py
- slac/bot/runIsrRunner_050.py
- slac/bot/runIsrRunner_051.py
- slac/bot/runIsrRunner_052.py
- slac/bot/runIsrRunner_053.py
- slac/bot/runIsrRunner_054.py
- slac/bot/runIsrRunner_055.py
- slac/bot/runIsrRunner_056.py
- slac/bot/runIsrRunner_057.py
- slac/bot/runIsrRunner_058.py
- slac/bot/runIsrRunner_059.py
- slac/bot/runIsrRunner_060.py
- slac/bot/runIsrRunner_061.py
- slac/bot/runIsrRunner_062.py
- slac/bot/runIsrRunner_063.py
- slac/bot/runIsrRunner_064.py
- slac/bot/runIsrRunner_065.py
- slac/bot/runIsrRunner_066.py
- slac/bot/runIsrRunner_067.py
- slac/bot/runIsrRunner_068.py
- slac/bot/runIsrRunner_069.py
- slac/bot/runIsrRunner_070.py
- slac/bot/runIsrRunner_071.py
- slac/bot/runIsrRunner_072.py
- slac/bot/runIsrRunner_073.py
- slac/bot/runIsrRunner_074.py
- slac/bot/runIsrRunner_075.py
- slac/bot/runIsrRunner_076.py
- slac/bot/runIsrRunner_077.py
- slac/bot/runIsrRunner_078.py
- slac/bot/runIsrRunner_079.py
- slac/bot/runIsrRunner_080.py
- slac/bot/runIsrRunner_081.py
- slac/bot/runIsrRunner_082.py
- slac/bot/runIsrRunner_083.py
- slac/bot/runIsrRunner_084.py
- slac/bot/runIsrRunner_085.py
- slac/bot/runIsrRunner_086.py
- slac/bot/runIsrRunner_087.py
- slac/bot/runIsrRunner_088.py
- slac/bot/runIsrRunner_089.py
- slac/bot/runIsrRunner_090.py
- slac/bot/runIsrRunner_091.py
- slac/bot/runIsrRunner_092.py
- slac/bot/runIsrRunner_093.py
- slac/bot/runIsrRunner_094.py
- slac/bot/runIsrRunner_095.py
- slac/bot/runIsrRunner_096.py
- slac/bot/runIsrRunner_097.py
- slac/bot/runIsrRunner_098.py
- slac/bot/runIsrRunner_099.py
- slac/bot/runIsrRunner_100.py
- slac/bot/runIsrRunner_101.py
- slac/bot/runIsrRunner_102.py
- slac/bot/runIsrRunner_103.py
- slac/bot/runIsrRunner_104.py
- slac/bot/runIsrRunner_105.py
- slac/bot/runIsrRunner_106.py
- slac/bot/runIsrRunner_107.py
- slac/bot/runIsrRunner_108.py
- slac/bot/runIsrRunner_109.py
- slac/bot/runIsrRunner_110.py
- slac/bot/runIsrRunner_111.py
- slac/bot/runIsrRunner_112.py
- slac/bot/runIsrRunner_113.py
- slac/bot/runIsrRunner_114.py
- slac/bot/runIsrRunner_115.py
- slac/bot/runIsrRunner_116.py
- slac/bot/runIsrRunner_117.py
- slac/bot/runIsrRunner_118.py
- slac/bot/runIsrRunner_119.py
- slac/bot/runIsrRunner_120.py
- slac/bot/runIsrRunner_121.py
- slac/bot/runIsrRunner_122.py
- slac/bot/runIsrRunner_123.py
- slac/bot/runIsrRunner_124.py
- slac/bot/runIsrRunner_125.py
- slac/bot/runIsrRunner_126.py
- slac/bot/runIsrRunner_127.py
- slac/bot/runIsrRunner_128.py
- slac/bot/runIsrRunner_129.py
- slac/bot/runIsrRunner_130.py
- slac/bot/runIsrRunner_131.py
- slac/bot/runIsrRunner_132.py
- slac/bot/runIsrRunner_133.py
- slac/bot/runIsrRunner_134.py
- slac/bot/runIsrRunner_135.py
- slac/bot/runIsrRunner_136.py
- slac/bot/runIsrRunner_137.py
- slac/bot/runIsrRunner_138.py
- slac/bot/runIsrRunner_139.py
- slac/bot/runIsrRunner_140.py
- slac/bot/runIsrRunner_141.py
- slac/bot/runIsrRunner_142.py
- slac/bot/runIsrRunner_143.py
- slac/bot/runIsrRunner_144.py
- slac/bot/runIsrRunner_145.py
- slac/bot/runIsrRunner_146.py
- slac/bot/runIsrRunner_147.py
- slac/bot/runIsrRunner_148.py
- slac/bot/runIsrRunner_149.py
- slac/bot/runIsrRunner_150.py
- slac/bot/runIsrRunner_151.py
- slac/bot/runIsrRunner_152.py
- slac/bot/runIsrRunner_153.py
- slac/bot/runIsrRunner_154.py
- slac/bot/runIsrRunner_155.py
- slac/bot/runIsrRunner_156.py
- slac/bot/runIsrRunner_157.py
- slac/bot/runIsrRunner_158.py
- slac/bot/runIsrRunner_159.py
- slac/bot/runIsrRunner_160.py
- slac/bot/runIsrRunner_161.py
- slac/bot/runIsrRunner_162.py
- slac/bot/runIsrRunner_163.py
- slac/bot/runIsrRunner_164.py
- slac/bot/runIsrRunner_165.py
- slac/bot/runIsrRunner_166.py
- slac/bot/runIsrRunner_167.py
- slac/bot/runIsrRunner_168.py
- slac/bot/runIsrRunner_169.py
- slac/bot/runIsrRunner_170.py
- slac/bot/runIsrRunner_171.py
- slac/bot/runIsrRunner_172.py
- slac/bot/runIsrRunner_173.py
- slac/bot/runIsrRunner_174.py
- slac/bot/runIsrRunner_175.py
- slac/bot/runIsrRunner_176.py
- slac/bot/runIsrRunner_177.py
- slac/bot/runIsrRunner_178.py
- slac/bot/runIsrRunner_179.py
- slac/bot/runIsrRunner_180.py
- slac/bot/runIsrRunner_181.py
- slac/bot/runIsrRunner_182.py
- slac/bot/runIsrRunner_183.py
- slac/bot/runIsrRunner_184.py
- slac/bot/runIsrRunner_185.py
- slac/bot/runIsrRunner_186.py
- slac/bot/runIsrRunner_187.py
- slac/bot/runIsrRunner_188.py
credentialFile: google_write_creds
vaultPrefixPath: secret/rubin/usdf-rubintv-broadcaster-cleanroom
pullSecretsPath: ts/software/nexus3-docker
rubinTvSecretsPath: ts/software/rubintv
credentialSecretsPath: rubintv-broadcaster
butlerSecret:
  key: butler-secret
  containerPath: /secrets
  dbUser: rubin
envSecrets:
- name: ASTROMETRY_NET_API_KEY
  secretName: rubintv
  secretKey: astrometry-net-api-key
imagePullSecrets:
- name: rubintv-broadcaster-pull-secret
pvcMountpoint:
- name: sdf-data-rubin
  containerPath: /repo
  subPath: repo
pvcMountpointClaim:
- name: sdf-group-rubin
  containerPath: /sdf/group/rubin
  claimSize: 1Gi
  accessMode: ReadWriteMany
- name: sdf-scratch
  containerPath: /scratch
  claimSize: 1Gi
  accessMode: ReadWriteMany
- name: fs-ddn-sdf-group-rubin
  containerPath: /fs/ddn/sdf/group/rubin
  claimSize: 1Gi
  accessMode: ReadWriteMany
- name: fs-ddn-sdf-group-lsst
  containerPath: /fs/ddn/sdf/group/lsst
  claimSize: 1Gi
  accessMode: ReadWriteMany
securityContext:
  uid: 15517
  gid: 4085
  fid: 4085
resources:
  requests:
    cpu: 1.0
    memory: "1G"
  limits:
    cpu: 1.0
    memory: "2G"
