image:
  repository: ts-dockerhub.lsst.org/dsm
  tag: c0028
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: tucson
  OSPL_INFOFILE: /tmp/ospl-info-dsm.log
  OSPL_ERRORFILE: /tmp/ospl-error-dsm.log
shmemDir: /run/ospl
osplVersion: V6.10.4
