image:
  repository: ts-dockerhub.lsst.org/atmcs_sim
  tag: c0015
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: base
  OSPL_INFOFILE: /tmp/ospl-info-atmcs.log
  OSPL_ERRORFILE: /tmp/ospl-error-atmcs.log
shmemDir: /run/ospl
osplVersion: V6.10.4
