# -- Set the replica count for the LOVE producers
replicaCount: 1
# -- The overall namespace for the LOVE producers
namespace: love
image:
  # -- The LOVE producer image to use
  repository: lsstts/love-producer
  # -- The tag to use for the LOVE producer image
  tag: develop
  # -- The pull policy on the LOVE producer image
  pullPolicy: IfNotPresent
  # -- The tag name for the Nexus3 Docker repository secrets if private images need to be pulled
  nexus3: nexus3-docker
# -- This section holds a set of key, value pairs for environmental variables
env:
  LSST_DDS_PARTITION_PREFIX: test
  WEBSOCKET_HOST: love-nginx/manager/ws/subscription
  OSPL_INFOFILE: /tmp/ospl-info-love-producer.log
  OSPL_ERRORFILE: /tmp/ospl-error-love-producer.log
# -- This section holds a set of key, value pairs for secrets
envSecrets:
  PROCESS_CONNECTION_PASS: manager-process-connection-password
# -- This sections sets the list of producers to use.
# The producers should be specified like:
# _name_: _CSC name:index_
# Example: ataos: ATAOS:0
producers: {}
# -- This is the version of the OpenSplice library to run. It is used to set the location of the OSPL configuration file
osplVersion: V6.10.4
# -- This is the path to the Kubernetes local store where the shared memory database will be written
shmemDir: /my/test
# -- This allows the specification of pod annotations.
podAnnotations: {}
# -- Resource specifications for the LOVE producer pods
resources: {}
# -- Node selection rules for the LOVE producer pods
nodeSelector: {}
# -- Toleration specifications for the LOVE producer pods
tolerations: []
# -- Affinity rules for the LOVE producer pods
affinity: {}
