image:
  repository: ts-dockerhub.lsst.org/love-producer
  tag: c0028
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: tucson
  WEBSOCKET_HOST: love-nginx-service/manager/ws/subscription
shmemDir: /run/ospl
producers:
  ataos: ATAOS:0
  atcamera: ATCamera:0
  atdome: ATDome:0
  atdometrajectory: ATDomeTrajectory:0
  atheaderservice: ATHeaderService:0
  athexapod: ATHexapod:0
  atmcs: ATMCS:0
  atpneumatics: ATPneumatics:0
  atocps: OCPS:1
  atoods: ATOODS:0
  atptg: ATPtg:0
  atscheduler: Scheduler:2
  atscriptqueue: ScriptQueue:2
  atspectrograph: ATSpectrograph:0
  authorize: Authorize:0
  camerahexapod: MTHexapod:1
  cccamera: CCCamera:0
  ccheaderservice: CCHeaderService:0
  ccocps: OCPS:2
  ccoods: CCOODS:0
  dimm1: DIMM:1
  dimm2: DIMM:2
  dsm1: DSM:1
  dsm2: DSM:2
  gcheaderservice1: GCHeaderService:1
  genericcamera1: GenericCamera:1
  love: LOVE:0
  m2hexapod: MTHexapod:2
  mtaircompressor1: MTAirCompressor:1
  mtaircompressor2: MTAirCompressor:2
  mtalignment: MTAlignment:0
  mtaos: MTAOS:0
  mtdome: MTDome:0
  mtdometrajectory: MTDomeTrajectory:0
  mtm1m3: MTM1M3:0
  mtm2: MTM2:0
  mtmount: MTMount:0
  mtptg: MTPtg:0
  mtrotator: MTRotator:0
  mtscheduler: Scheduler:1
  mtscriptqueue: ScriptQueue:1
  watcher: Watcher:0
  weatherstation1: WeatherStation:1
osplVersion: V6.10.4
