image:
  repository: ts-dockerhub.lsst.org/watcher
  tag: c0028
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  RUN_ARG: --state enabled
  LSST_DDS_PARTITION_PREFIX: tucson
  LSST_SITE: tucson
  OSPL_INFOFILE: /tmp/ospl-info-watcher.log
  OSPL_ERRORFILE: /tmp/ospl-error-watcher.log
shmemDir: /run/ospl
osplVersion: V6.10.4
