env: summit
namespace: eas
cscs:
  - dimm1
  - dimm2
  - hvac
  - ess1
  - ess101
  - ess102
  - ess103
  - ess104
  - ess201
  - ess202
  - ess203
  - ess204
  - ess301
  - weatherforecast
renameMap:
  ess1: tma-ess01
  ess101: mtdome-ess01
  ess102: mtdome-ess02
  ess103: mtdome-ess03
  ess104: tma-ess104
  ess201: auxtel-ess01
  ess202: auxtel-ess02
  ess203: auxtel-ess03
  ess204: auxtel-ess04
  ess301: calibhill-ess01
