env: tucson-teststand
cscs:
  - ataos
  - atdome
  - atdometrajectory
  - atheaderservice
  - athexapod
  - atoods
  - atptg
  - atspectrograph
  - hexapodsim
isSim:
  - atdome
  - athexapod
  - atspectrograph
renameMap:
  hexapodsim: hexapod-sim
