image:
  repository: ts-dockerhub.lsst.org/lasertracker
  tag: c0029
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: summit
  LSST_SITE: summit
  OSPL_INFOFILE: /tmp/ospl-info-lasertracker.log
  OSPL_ERRORFILE: /tmp/ospl-error-lasertracker.log
shmemDir: /run/ospl
osplVersion: V6.10.4
