csc:
  image:
    repository: ts-dockerhub.lsst.org/mtmount
    tag: c0020
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_PARTITION_PREFIX: summit
    RUN_ARG: --simulate
  shmemDir: /run/ospl
  osplVersion: V6.10.4
ingress:
  use: false
  hostname: mtmount.cp.lsst.org
  port: 8000
