image:
  repository: ts-dockerhub.lsst.org/weatherforecast
  tag: c0029
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: tucson
  LSST_SITE: tucson
  RUN_ARG: --state enabled
  OSPL_INFOFILE: /tmp/ospl-info-weatherforecast.log
  OSPL_ERRORFILE: /tmp/ospl-error-weatherforecast.log
envSecrets:
- name: METEOBLUE_API_KEY
  secretName: meteoblue
  secretKey: api-key
shmemDir: /run/ospl
osplVersion: V6.10.4
