namespace: auxtel
image:
  repository: ts-dockerhub.lsst.org/athexapod
  tag: c0029
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: summit
  LSST_SITE: summit
  OSPL_INFOFILE: /tmp/ospl-info-athexapod.log
  OSPL_ERRORFILE: /tmp/ospl-error-athexapod.log
shmemDir: /run/ospl
annotations:
  k8s.v1.cni.cncf.io/networks: kube-system/macvlan-conf
useMulticast: true
initContainer:
  repository: lsstit/ddsnet4u
  tag: latest
  pullPolicy: Always
osplVersion: V6.10.4
