image:
  repository: ts-dockerhub.lsst.org/mtdome
  tag: c0027
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: summit
  LSST_SITE: summit
  OSPL_INFOFILE: /tmp/ospl-info-mtdome.log
  OSPL_ERRORFILE: /tmp/ospl-error-mtdome.log
  RUN_ARG: --simulate
shmemDir: /run/ospl
osplVersion: V6.10.4
