image:
  repository: ts-dockerhub.lsst.org/mtrotator
  tag: c0028
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: summit
  LSST_SITE: summit
  OSPL_INFOFILE: /tmp/ospl-info-mtrotator.log
  OSPL_ERRORFILE: /tmp/ospl-error-mtrotator.log
shmemDir: /run/ospl
osplVersion: V6.10.4
