namespace: maintel
image:
  repository: ts-dockerhub.lsst.org/rotator
  tag: c0028
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: base
  LSST_SITE: base
  OSPL_INFOFILE: /tmp/ospl-info-mtrotator.log
  OSPL_ERRORFILE: /tmp/ospl-error-mtrotator.log
  RUN_ARG: --simulate
shmemDir: /run/ospl
osplVersion: V6.10.4
