env: summit
namespace: calsys
cscs:
  - electrometer1
  - electrometer201
  - atwhitelight
  - atmonochromator
  - gcheaderservice1
renameMap:
  electrometer1: comcam-electrometer
  electrometer201: auxtel-electrometer-201
