csc:
  image:
    repository: ts-dockerhub.lsst.org/headerservice
    tag: ts-v2.9.1_salobj_v6.4.1_idl_v3.1.3_xml_v9.1.1_c0021
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_PARTITION_PREFIX: summit
    LSST_DDS_RESPONSIVENESS_TIMEOUT: 15s
    URL_SPEC: --lfa_mode s3 --s3instance cp
    S3_ENDPOINT_URL: https://s3.cp.lsst.org/
  envSecrets:
  - name: AWS_ACCESS_KEY_ID
    secretName: lfa
    secretKey: aws-access-key-id
  - name: AWS_SECRET_ACCESS_KEY
    secretName: lfa
    secretKey: aws-secret-access-key
  - name: MYS3_ACCESS_KEY
    secretName: lfa
    secretKey: aws-access-key-id
  - name: MYS3_SECRET_KEY
    secretName: lfa
    secretKey: aws-secret-access-key
  pvcMountpoint:
  - name: www
    path: /home/saluser/www
    accessMode: ReadWriteOnce
    claimSize: 50Gi
  shmemDir: /run/ospl
  osplVersion: V6.10.4
ingress:
  use: false
  hostname: ccheaderservice.cp.lsst.org
  port: 8000
