namespace: maintel
image:
  repository: ts-dockerhub.lsst.org/mtdometrajectory
  tag: c0015
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: base
  OSPL_INFOFILE: /tmp/ospl-info-mtdometrajectory.log
  OSPL_ERRORFILE: /tmp/ospl-error-mtdometrajectory.log
shmemDir: /run/ospl
osplVersion: V6.10.4
