image:
  repository: ts-dockerhub.lsst.org/at_pneumatics_sim
  tag: c0028
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: tucson
  OSPL_INFOFILE: /tmp/ospl-info-atpneumatics.log
  OSPL_ERRORFILE: /tmp/ospl-error-atpneumatics.log
shmemDir: /run/ospl
osplVersion: V6.10.4
